---
client_id: ''
client_secret: ''
verification_token: ''

port: 3000
redirect_uri: ''

email:
  use: false
  smtp:
    host: smtp.gmail.com
    port: 465
    ssl: true
    auth:
      user: 'user-name@gmail.com'
      pass: 'user-password'
  from: 'sendFrom@mail.com'
  to: 'sendTo@mail.com'
